-- migrations/001_initial.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Postgres (Neon) schema for scan sessions, ported from the SQLite schema in
-- core/store.py (_SCHEMA). Run once against a fresh Neon branch:
--
--     psql "$NEON_DATABASE_URL" -v ON_ERROR_STOP=1 -f migrations/001_initial.sql
--
-- Idempotent (IF NOT EXISTS throughout), so re-running is harmless.
--
-- Deliberate differences from the SQLite original, each of which needs a
-- matching change in core/store.py when that module is ported to psycopg:
--
--   * Timestamps are timestamptz, not ISO-8601 TEXT. Retention and the
--     board's since_days filter both compare timestamps; on TEXT those only
--     worked by accident of ISO-8601 sorting lexicographically, and could not
--     use interval arithmetic. The driver now returns real datetime objects.
--   * on_hold is boolean, not the 0/1 INTEGER that core/store.record_scan
--     writes via int(bool(...)).
--   * The scan -> session foreign key is ON DELETE CASCADE, so retention is a
--     single DELETE against `session` (see scripts/purge_expired.sql) instead
--     of the two-step collect-ids-then-delete-both that
--     core/store.purge_old_sessions has to do today.

BEGIN;

CREATE TABLE IF NOT EXISTS session (
    session_id  text PRIMARY KEY,
    sanford_id  text,
    location    text,
    -- Only 'active' and 'ended' are ever stored. STALE is derived at read
    -- time from the last scan's age, never persisted — see the core/store.py
    -- module docstring and session_is_stale().
    status      text NOT NULL CHECK (status IN ('active', 'ended')),
    created_at  timestamptz NOT NULL,
    ended_at    timestamptz
);

CREATE TABLE IF NOT EXISTS scan (
    -- BY DEFAULT rather than ALWAYS so rows can be inserted with an explicit
    -- id if history is ever backfilled from the old SQLite file. After such a
    -- backfill the sequence must be advanced past the highest id:
    --   SELECT setval(pg_get_serial_sequence('scan', 'id'), max(id)) FROM scan;
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    text NOT NULL REFERENCES session (session_id) ON DELETE CASCADE,
    scanned_at    timestamptz NOT NULL,
    last_scanned  timestamptz NOT NULL,
    scan_count    integer NOT NULL DEFAULT 1,
    gtin          text,
    raw_scan      text,
    status_key    text,
    source        text,
    on_hold       boolean,
    item          text,
    company       text,
    brand         text,
    description   text,
    gtin_uom      text,
    uou           text,
    hibcc         text,
    lawson_id     text,
    lawson_uom    text
);

-- Serves core/store.find_scan's (session_id, gtin) dedupe lookup, and — because
-- session_id is the leading column — also every session_id-only lookup that
-- SQLite needed a second index for. Postgres does not automatically index
-- foreign key columns, so this index is additionally what keeps the ON DELETE
-- CASCADE from retention a sane index scan instead of a full seq scan of
-- `scan` per deleted session.
--
-- The old idx_scan_session is therefore intentionally not recreated here: a
-- btree on (session_id, gtin) already answers everything it did.
CREATE INDEX IF NOT EXISTS idx_scan_dedupe ON scan (session_id, gtin);

-- Serves both the board's `created_at >= cutoff` filter (core/store.list_sessions)
-- and the retention sweep's `created_at < cutoff`.
CREATE INDEX IF NOT EXISTS idx_session_created ON session (created_at);

COMMIT;

-- ── Optional hardening, not enabled ─────────────────────────────────────────
-- core/store.record_scan is only ever called after find_scan() returns None,
-- so (session_id, gtin) is meant to be unique. It is not enforced, and two
-- scans arriving close enough together can both pass the check and insert
-- duplicate rows — more likely now that scans auto-submit. Enforcing it:
--
--   CREATE UNIQUE INDEX CONCURRENTLY idx_scan_dedupe_uniq ON scan (session_id, gtin);
--
-- only makes sense together with rewriting record_scan as an upsert, since
-- otherwise the losing insert raises instead of incrementing:
--
--   INSERT INTO scan (...) VALUES (...)
--   ON CONFLICT (session_id, gtin)
--   DO UPDATE SET scan_count = scan.scan_count + 1, last_scanned = EXCLUDED.last_scanned;
--
-- which would also collapse record_scan and increment_scan into one round trip.
-- Left out here to keep this migration behaviour-preserving.
