-- migrations/004_usage_dashboard.sql
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Schema for the owner-only usage/security dashboard (pages/usage_dashboard.py):
-- a durable daily rollup, plus a log of GoodID fallback lookups. Run against
-- the same Neon branch as 001-003:
--
--     psql "$NEON_DATABASE_URL" -v ON_ERROR_STOP=1 -f migrations/004_usage_dashboard.sql
--
-- Idempotent (IF NOT EXISTS throughout), so re-running is harmless.
--
-- WHY A SEPARATE ROLLUP TABLE
--
-- `session` and `scan` are swept by the daily retention purge (core/store.py:
-- RETENTION_DAYS = 3, scripts/purge_expired.sql) — three days after a shift,
-- the raw rows a "how many people used this today" query would need are
-- gone. A same-day dashboard could still query `session` directly, but a
-- baseline ("normally 30-50/day, is today's 200 an anomaly?") needs history
-- that outlives the purge. daily_usage_stats is that history: one row per
-- day, written by a nightly rollup (scripts/rollup_daily_stats.sql via
-- .github/workflows/rollup-daily-stats.yml) BEFORE that day's raw rows age
-- out, and never itself purged.
--
-- WHY goodid_lookup_log
--
-- api/goodid_client.py's AccessGUDID fallback calls only ever reached the
-- Python logger (stdout), not the database — there was no queryable history
-- of lookup success/failure. A sudden burst of failed/rate-limited lookups is
-- a stronger attack signal than a raw user-count spike (see the dashboard's
-- module docstring), so each call is now logged here. No GTIN or other scan
-- content is stored — the dashboard only needs volume and outcome, not what
-- was looked up.

BEGIN;

CREATE TABLE IF NOT EXISTS daily_usage_stats (
    day             date PRIMARY KEY,
    unique_users    integer NOT NULL,
    session_count   integer NOT NULL,
    scan_count      integer NOT NULL,
    goodid_lookups  integer NOT NULL DEFAULT 0,
    goodid_failures integer NOT NULL DEFAULT 0,
    computed_at     timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS goodid_lookup_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queried_at  timestamptz NOT NULL,
    success     boolean NOT NULL,
    status_code integer,
    error_type  text
);

-- Serves both the rollup's `queried_at >= day_start AND < day_end` scan and
-- the dashboard's own trailing-window read.
CREATE INDEX IF NOT EXISTS idx_goodid_lookup_log_queried_at
    ON goodid_lookup_log (queried_at);

COMMIT;

-- ── Retention for goodid_lookup_log ─────────────────────────────────────────
-- Not swept by scripts/purge_expired.sql (that targets `session`/`scan`
-- only) and not wired into a purge job here — fallback lookups are rare
-- enough (only reached on a contract-file miss) that row volume stays small.
-- If that stops being true, add a companion DELETE keyed on queried_at
-- alongside the existing retention sweep rather than inventing a second
-- schedule.
